---

- hosts: ee
  tasks:
    - name: get kerberos admin password
      ansible.builtin.command:
        argv:
          - '{{ pass_cmd }}'
          - kerberos/ee.cooper.edu
      register: kerberos_admin_password
      delegate_to: localhost
      changed_when: false

- hosts: all
  tasks:
    - name: register retrieved passwords
      ansible.builtin.set_fact:
        # yamllint disable-line rule:line-length
        password: {kerberos: '{{ kerberos_admin_password.stdout | default("") }}'}
        ipaadmin_password: '{{ kerberos_admin_password.stdout | default("") }}'
