---

- hosts: all
  become: true
  roles:
    - repo/microsoft

- hosts: gentoo
  become: true
  roles:
    - distro/gentoo/portage
    - distro/gentoo/crossdev

- hosts: all
  become: true
  roles:
    - sys/time

- hosts: ee
  become: true
  roles:
    - freeipa.ansible_freeipa.ipaclient
