---

- import_playbook: 'pass.yml'
  when: pass | default(false) | bool

- import_playbook: 'pre_tasks.yml'

- hosts: 'all'
  become: true
  roles:
    - 'common'
    - 'net/firewall'

- hosts: 'ee'
  become: true
  roles:
    - 'net/ssh'
    - 'pkg/build'
    - 'pkg/can'
    - 'pkg/container'
    - 'pkg/editor'

- hosts: 'cs102'
  become: true
  roles:
    - 'course/cs102'
    - 'pkg/build'
    - 'pkg/editor'
