---

- import_playbook: 'pass.yml'
  when: pass | default(false) | bool

- import_playbook: 'pre_tasks.yml'

- hosts: 'all'
  become: true
  roles:
    - 'common'

- hosts: 'ufw'
  become: true
  roles:
     - 'net/firewall'

- hosts: 'firewalld'
  become: true
  roles:
     - 'net/firewalld'

- hosts: 'ee'
  become: true
  roles:
    - 'net/ssh'
    - 'pkg/build'
    - 'pkg/editor'

- hosts: 'autonomylab'
  become: true
  roles:
    - 'pkg/container'
    - 'pkg/can'

- hosts: 'cs102'
  become: true
  roles:
    - 'course/cs102'
    - 'pkg/build'
    - 'pkg/editor'

- hosts: 'mudbug'
  become: true
  roles:
    - 'distro/fedora/gnome'
    - 'distro/fedora/grubby'
    - 'fs/auristorfs'
    - 'orgs/mudbug'
