---

- import_playbook: 'pre_tasks.yml'

- hosts: 'all'
  become: true
  roles:
    - 'common'
    - 'sys/time'

- hosts: 'ee'
  become: true
  roles:
    - 'net/ssh'

- hosts: 'cs102'
  become: true
  roles:
    - 'course/cs102'
