---

- import_playbook: 'pre_tasks.yml'

- hosts: 'all'
  become: true
  roles:
    - 'common'

- hosts: 'ee'
  become: true
  roles:
    - 'net/ssh'
    - 'pkg/build'
    - 'pkg/can'
    - 'pkg/container'

- hosts: 'cs102'
  become: true
  roles:
    - 'course/cs102'
    - 'pkg/build'
