---
# Main tasks file, updates packages and stuff

# distro upgrade first!
- name: ensure everything's upgraded
  apt:
    update_cache: yes
    upgrade: dist

# now, packages
- name: install tmux
  apt:
    name: tmux
    state: latest
  notify: check if anyone actually notifies this
- name: install gcc
  apt:
    name: gcc
    state: latest
- name: install g++
  apt:
    name: g++
    state: latest
- name: install tree
  apt:
    name: tree
    state: latest
- name: install make
  apt:
    name: make
    state: latest

# cbonsai, as an exercise in building stuff from source
- name: install libncurses-dev
  apt:
    name: libncurses-dev
    state: latest
- name: install git
  apt:
    name: git
    state: latest
- name: clone cbonsai source
  git:
    repo: https://gitlab.com/jallbrit/cbonsai
    dest: /root/source-builds/cbonsai
- name: build and install cbonsai
  command:
    cmd: /usr/bin/make install
    chdir: /root/source-builds/cbonsai
    creates: /usr/local/bin/cbonsai
