---

autonomylab:
  children:

    ctrls:
      hosts:
        ctrls-heehee.host.autonomylab.nyc:

    dbw:
      hosts:
        dbw-gucci.host.autonomylab.nyc:
        dbw-prada.host.autonomylab.nyc:
