---

ulab:
  children:

    conway:
      hosts:
        conway.ee.cooper.edu: ~

    dev:
      hosts:
        dev.ee.cooper.edu: ~

    mudbug:
      hosts:
        mudbug1.ee.cooper.edu: ~
        mudbug2.ee.cooper.edu: ~
        mudbug3.ee.cooper.edu: ~
        mudbug4.ee.cooper.edu: ~
