---

- name: 'include OS-specific vars'
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
      - '{{ ansible_distribution }}.yml'
      skip: true

- name: 'install build tools'
  ansible.builtin.package:
    name: '{{ item }}'
    state: 'present'
  with_items: '{{ packages_build }}'

- name: 'install c tools'
  ansible.builtin.package:
    name: '{{ item }}'
    state: 'present'
  with_items: '{{ packages_c }}'

- name: 'install python3 tools'
  ansible.builtin.package:
    name: '{{ item }}'
    state: 'present'
  with_items: '{{ packages_python3 }}'
