---

# community.general.parted is horrible and can go to hell
# sfdisk is also quite annoying to use
# we instead script fdisk...

- name: create empty GPT disklabel
  ansible.builtin.shell:
    cmd: echo -e 'g\nw\n' | fdisk {{ install_device }}

- name: create boot partition
  ansible.builtin.shell:
    # yamllint disable-line rule:line-length
    cmd: echo -e 'n\n1\n\n+{{ boot_partition_size }}\nw\n' | fdisk {{ install_device }}

- name: create primary partition
  ansible.builtin.shell:
    cmd: echo -e 'n\n2\n\n\nw\n' | fdisk {{ install_device }}

- name: mark boot partition as EFI type
  ansible.builtin.shell:
    cmd: echo -e 't\n1\n1\nw\n' | fdisk {{ install_device }}

- name: get partition_paths
  ansible.builtin.shell:
    cmd: fdisk -l {{ install_device }} | tail -n2 | awk '{ print $1 }'
  changed_when: false
  register: partition_paths

- name: register boot partition path
  ansible.builtin.set_fact:
    boot_partition: '{{ partition_paths.stdout_lines[0] }}'

- name: register primary partition path
  ansible.builtin.set_fact:
    primary_partition: '{{ partition_paths.stdout_lines[1] }}'
