- name: 'install Docker'
  ansible.builtin.package:
    name: '{{ package_docker }}'
    state: 'present'

- name: 'install Docker Compose'
  ansible.builtin.package:
    name: '{{ package_docker_compose }}'
    state: 'present'

- name: 'install Podman'
  ansible.builtin.package:
    name: '{{ package_podman }}'
    state: 'present'

- name: 'enable Docker daemon (`{{ docker_daemon }}`)'
  ansible.builtin.service:
    enabled: true
    name: '{{ docker_daemon }}'
    state: 'started'
