---

# c
package_binutils: binutils
package_clang: clang
package_gcc: gcc
package_gdb: gdb
package_linux_headers: linux-headers
package_valgrind: valgrind

packages_c:
  - '{{ package_binutils }}'
  - '{{ package_clang }}'
  - '{{ package_gcc }}'
  - '{{ package_gdb }}'
  - '{{ package_linux_headers }}'
  - '{{ package_valgrind }}'

# python3
package_python3: python3
package_python3_distutils: python3-distutils
package_python3_pip: python3-pip
package_python3_venv: python3-venv
package_python3_wheel: python3-wheel

packages_python3:
  - '{{ package_python3 }}'
  - '{{ package_python3_distutils }}'
  - '{{ package_python3_pip }}'
  - '{{ package_python3_venv }}'
  - '{{ package_python3_wheel }}'
