---

- name: 'install nft-utils'
  ansible.builtin.package:
    name: '{{ package_nfs_utils }}'
    state: 'present'

- name: 'ensure `{{ nfs_mnt_point }}` exists'
  ansible.builtin.file:
    path: '{{ nfs_mnt_point }}'
    state: 'directory'

- name: 'mount `{{ nfs_share }}` to `{{ nfs_mnt_point }}`'
  ansible.posix.mount:
    src: '{{ nfs_share }}'
    path: '{{ nfs_mnt_point }}'
    fstype: 'nfs'
    state: 'mounted'
