---

- name: include OS-specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}.yml'
      skip: true

- name: install goodies
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items: '{{ packages_goodies }}'

- name: install shells
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items: '{{ packages_shells }}'

- name: install utils
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items: '{{ packages_utils }}'

- name: install greet script
  ansible.builtin.copy:
    src: res/ulab.sh
    dest: /etc/profile.d/ulab.sh
    mode: 0755

- name: include OS-specific tasks
  ansible.builtin.include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}.yml'
      skip: true
