---

- name: ensure Microsoft apt key is present
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/packages.microsoft.asc
    owner: root
    group: root
    mode: 0644

- name: add Microsoft apt repo
  ansible.builtin.apt_repository:
    filename: packages.microsoft
    # yamllint disable-line rule:line-length
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.asc]
      https://packages.microsoft.com/repos/code stable main
    state: present
